# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName("mainWin")
        mainWin.resize(706, 639)
        self.centralwidget = QtWidgets.QWidget(mainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 611, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rest_ip = QtWidgets.QLineEdit(self.layoutWidget)
        self.rest_ip.setObjectName("rest_ip")
        self.horizontalLayout.addWidget(self.rest_ip)
        self.Port = QtWidgets.QLabel(self.layoutWidget)
        self.Port.setObjectName("Port")
        self.horizontalLayout.addWidget(self.Port)
        self.rest_port = QtWidgets.QLineEdit(self.layoutWidget)
        self.rest_port.setObjectName("rest_port")
        self.horizontalLayout.addWidget(self.rest_port)
        self.connect = QtWidgets.QPushButton(self.layoutWidget)
        self.connect.setObjectName("connect")
        self.horizontalLayout.addWidget(self.connect)
        self.Disconnect = QtWidgets.QPushButton(self.layoutWidget)
        self.Disconnect.setObjectName("Disconnect")
        self.horizontalLayout.addWidget(self.Disconnect)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(19, 180, 609, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.individual_1 = QtWidgets.QLabel(self.frame)
        self.individual_1.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.individual_1.setFont(font)
        self.individual_1.setObjectName("individual_1")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_1.setGeometry(QtCore.QRect(140, 10, 401, 61))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.show_1 = QtWidgets.QPushButton(self.frame)
        self.show_1.setGeometry(QtCore.QRect(540, 20, 61, 51))
        self.show_1.setObjectName("show_1")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 500, 609, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.individual_5 = QtWidgets.QLabel(self.frame_5)
        self.individual_5.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.individual_5.setFont(font)
        self.individual_5.setObjectName("individual_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_5.setGeometry(QtCore.QRect(140, 10, 401, 61))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.show_5 = QtWidgets.QPushButton(self.frame_5)
        self.show_5.setGeometry(QtCore.QRect(540, 20, 61, 51))
        self.show_5.setObjectName("show_5")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(19, 340, 609, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.individual_3 = QtWidgets.QLabel(self.frame_3)
        self.individual_3.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.individual_3.setFont(font)
        self.individual_3.setObjectName("individual_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(140, 10, 401, 61))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.show_3 = QtWidgets.QPushButton(self.frame_3)
        self.show_3.setGeometry(QtCore.QRect(540, 20, 61, 51))
        self.show_3.setObjectName("show_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 420, 609, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.individual_4 = QtWidgets.QLabel(self.frame_4)
        self.individual_4.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.individual_4.setFont(font)
        self.individual_4.setObjectName("individual_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_4.setGeometry(QtCore.QRect(140, 10, 401, 61))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.show_4 = QtWidgets.QPushButton(self.frame_4)
        self.show_4.setGeometry(QtCore.QRect(540, 20, 61, 51))
        self.show_4.setObjectName("show_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(19, 260, 609, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.individual_2 = QtWidgets.QLabel(self.frame_2)
        self.individual_2.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.individual_2.setFont(font)
        self.individual_2.setObjectName("individual_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(140, 10, 401, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.show_2 = QtWidgets.QPushButton(self.frame_2)
        self.show_2.setGeometry(QtCore.QRect(540, 20, 61, 51))
        self.show_2.setObjectName("show_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 90, 611, 90))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.totaltimecost = QtWidgets.QLabel(self.widget)
        self.totaltimecost.setObjectName("totaltimecost")
        self.gridLayout.addWidget(self.totaltimecost, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.population = QtWidgets.QLabel(self.widget)
        self.population.setObjectName("population")
        self.gridLayout.addWidget(self.population, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.bestfitness = QtWidgets.QLabel(self.widget)
        self.bestfitness.setObjectName("bestfitness")
        self.gridLayout.addWidget(self.bestfitness, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.bestsolution = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bestsolution.sizePolicy().hasHeightForWidth())
        self.bestsolution.setSizePolicy(sizePolicy)
        self.bestsolution.setObjectName("bestsolution")
        self.gridLayout.addWidget(self.bestsolution, 3, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 611, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.data_path_label = QtWidgets.QLabel(self.widget1)
        self.data_path_label.setObjectName("data_path_label")
        self.horizontalLayout_2.addWidget(self.data_path_label)
        self.data_path_text = QtWidgets.QLineEdit(self.widget1)
        self.data_path_text.setObjectName("data_path_text")
        self.horizontalLayout_2.addWidget(self.data_path_text)
        self.submit_data = QtWidgets.QPushButton(self.widget1)
        self.submit_data.setObjectName("submit_data")
        self.horizontalLayout_2.addWidget(self.submit_data)
        self.start = QtWidgets.QPushButton(self.widget1)
        self.start.setObjectName("start")
        self.horizontalLayout_2.addWidget(self.start)
        mainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        mainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWin)
        self.statusbar.setObjectName("statusbar")
        mainWin.setStatusBar(self.statusbar)

        self.retranslateUi(mainWin)
        QtCore.QMetaObject.connectSlotsByName(mainWin)

    def retranslateUi(self, mainWin):
        _translate = QtCore.QCoreApplication.translate
        mainWin.setWindowTitle(_translate("mainWin", "Evaluationary Monitor"))
        self.label.setText(_translate("mainWin", "REST IP:"))
        self.Port.setText(_translate("mainWin", "Port:"))
        self.connect.setText(_translate("mainWin", "Connect"))
        self.Disconnect.setText(_translate("mainWin", "Disconnect"))
        self.individual_1.setText(_translate("mainWin", "Individual No.1 :"))
        self.show_1.setText(_translate("mainWin", "Show"))
        self.individual_5.setText(_translate("mainWin", "Individual No.5 :"))
        self.show_5.setText(_translate("mainWin", "Show"))
        self.individual_3.setText(_translate("mainWin", "Individual No.3 :"))
        self.show_3.setText(_translate("mainWin", "Show"))
        self.individual_4.setText(_translate("mainWin", "Individual No.4 :"))
        self.show_4.setText(_translate("mainWin", "Show"))
        self.individual_2.setText(_translate("mainWin", "Individual No.2 :"))
        self.show_2.setText(_translate("mainWin", "Show"))
        self.label_2.setText(_translate("mainWin", "Total Time Cost : "))
        self.totaltimecost.setText(_translate("mainWin", "0"))
        self.label_3.setText(_translate("mainWin", "Population :"))
        self.population.setText(_translate("mainWin", "50"))
        self.label_4.setText(_translate("mainWin", "Best Fitness :"))
        self.bestfitness.setText(_translate("mainWin", "0"))
        self.label_5.setText(_translate("mainWin", "Best solution : "))
        self.bestsolution.setText(_translate("mainWin", "[ ]"))
        self.data_path_label.setText(_translate("mainWin", "Data Path :"))
        self.submit_data.setText(_translate("mainWin", "Submit"))
        self.start.setText(_translate("mainWin", "Start"))
